# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e201a71f380a398bbb5649e256c6cca6f8137e6c2e397d12cff9ee789768f4318089afa352b96ab157bb650c386c37010dfedc6ec22c444607cc9abb0b22f031

test:
  secret_key_base: 13cf7131e9bee14be134b6e8fb0116e0c911fd461f3e5fb22af9d03e131e9c34c9b03e7eb0eb72e0ea141a5c10c8e0160d2004ab2b2f92fcb9df3249ff2751d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
